# Generated by Django 2.0.7 on 2018-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.PositiveIntegerField()),
                ('construccion', models.PositiveIntegerField()),
                ('recamaras', models.PositiveIntegerField()),
                ('banios', models.PositiveIntegerField()),
                ('precio', models.PositiveIntegerField()),
                ('foto', models.ImageField(upload_to='uploads/')),
                ('calle', models.CharField(max_length=30)),
                ('noExterior', models.CharField(max_length=30)),
                ('noInterior', models.CharField(blank=True, max_length=30)),
                ('colonia', models.CharField(max_length=30)),
                ('delegacion', models.CharField(max_length=30)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('habilitada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'propiedades',
            },
        ),
    ]
